=== jegasuguna/xml_xsd/xmlSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/myxmlSchema" xmlns:tns="http://www.example.org/myxmlSchema" elementFormDefault="qualified">


    
    


    <element name="root" type="tns:rootType"></element>
    
    <complexType name="rootType">
    	<sequence>
    		<element name="parent" type="tns:parentType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="parent"></complexType>

    <complexType name="parentType">
    	<sequence>
    		<element name="attribute1" type="tns:attributeType"
    			maxOccurs="unbounded" minOccurs="2">
    		</element>
    		<element name="attribute2" type="tns:attributeType2" maxOccurs="unbounded" minOccurs="2"></element>
    	</sequence>
    	
    	
    </complexType>

    <complexType name="attributeType"></complexType>

    <complexType name="attributeType2"></complexType>
</schema>

=== jegasuguna/xml_xsd/NewFile1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:root xmlns:tns="http://www.example.org/myxmlSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/myxmlSchema xmlSchema.xsd ">
  <tns:parent>
    <tns:attribute1/>
    <tns:attribute1/>
    <tns:attribute2/>
    <tns:attribute2/>
  </tns:parent>
  <tns:parent>
    <tns:attribute1/>
    <tns:attribute1/>
    <tns:attribute2/>
    <tns:attribute2/>
  </tns:parent>
</tns:root>
